# Generated by Django 4.1 on 2024-03-03 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubwayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_id",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(523)],
                    ),
                ),
                ("complex_id", models.IntegerField(default=-1)),
                (
                    "gtfs_stop_id",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "line",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "stop_name",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "borough",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "daytime_routes",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "gtfs_latitude",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "gtfs_longitude",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "north_direction_label",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "south_direction_label",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "ada",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(2)],
                    ),
                ),
                (
                    "ada_notes",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                (
                    "georeference",
                    models.CharField(
                        default="No information available", max_length=700
                    ),
                ),
                ("lon", models.FloatField(default=-1)),
                ("lat", models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mainmap.subwaystation",
                    ),
                ),
            ],
        ),
    ]
