# Generated by Django 4.1 on 2023-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaystations',
            name='equipmentno',
            field=models.CharField(default='No information available', max_length=250),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='shortdescription',
            field=models.CharField(default='No information available', max_length=250),
        ),
    ]
