# Generated by Django 4.1 on 2023-11-16 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_subwaystations_equipmentno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwaystations',
            name='equipmentno',
        ),
        migrations.RemoveField(
            model_name='subwaystations',
            name='shortdescription',
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='ada',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='ada_notes',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='borough',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='community_feedback',
            field=models.TextField(default='Enter advice to the community about this station here.'),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='complex_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='daytime_routes',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='division',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='georeference',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='gtfs_latitude',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='gtfs_longitude',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='gtfs_stop_id',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='line',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='north_direction_label',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='south_direction_label',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='station_id',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(523)]),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='stop_name',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AddField(
            model_name='subwaystations',
            name='structure',
            field=models.CharField(default='No information available', max_length=700),
        ),
        migrations.AlterField(
            model_name='subwaystations',
            name='lat',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='subwaystations',
            name='lon',
            field=models.FloatField(default=-1),
        ),
    ]
