# Generated by Django 4.1 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_subwaystations_all_comm_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaystations',
            name='all_comm_feedback',
            field=models.TextField(null=True),
        ),
    ]
