# Generated by Django 4.1 on 2023-11-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_subwaystations_all_comm_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaystations',
            name='all_comm_feedback',
            field=models.TextField(default='Community feedback will appear below here when you fill out the form below', null=True),
        ),
    ]
