# Generated by Django 4.1 on 2024-02-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_subwaystations_all_comm_feedback"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubwayStations",
            new_name="SubwayStation",
        ),
    ]
