# Generated by Django 4.1 on 2024-02-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_rename_subwaystations_subwaystation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subwaystation",
            name="all_comm_feedback",
        ),
        migrations.RemoveField(
            model_name="subwaystation",
            name="community_feedback",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pages.subwaystation",
                    ),
                ),
            ],
        ),
    ]
