# Generated by Django 4.1 on 2024-02-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_remove_subwaystation_all_comm_feedback_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Feedback",
        ),
    ]
